export default `/*********************************************
 
            !!!!! WARNING !!!!! 
DO NOT EDIT THIS FILE, THESE ARE SHARED TYPES 
BETWEEN CLIENT AND FEATHERS
IF YOU NEED TO ADD SOMETHING TO THIS FILE ADD
WITH https://github.com/eduardomar/cc15-dis
**********************************************/`.trim();
